### ISSUE TITLE
Support for unary and ternary operators

### ISSUE THREAD

**Issue by pushpakrajgautam** [d3lio/lexpar#2]
Hi!

First of all, this is an awesome crate and is very useful. There is one thing that is bugging me about it though and I've described my dilemma below. 

I was wondering whether the parse_rules! macro supports unary and ternary operators. What I mean is that whether there is a way to provide operator precedence for all sorts of operators together: unary, binary, ternary. The crate does a great job in specifying operator precedence for binary operators, but I'm not sure how to include some other operators (unary, ternary) .

Another thing is whether I can specify associativity of operators. Here is a link that shows C's operator precedence (with associativity) : https://en.cppreference.com/w/c/language/operator_precedence

I'm writing a DSL, and part of it involves specifying operator precedence in the manner of the above link.

It would be great if you could help me figure this part out. If the existing macro can't handle the need described above, do you think a slight amount of tweaking in the parse_rules! macro would help?

Looking forward to hearing from you, and let me know if I should provide more context. Thanks!

**Comment by d3lio** [comment]
Hey, thanks for the interest in the library, here's what you can do:

For unary operators check the docs: https://docs.rs/lexpar/0.1.0/lexpar/parser/index.html#unary-operators
The higher defined operator will have hieher precedence. You can define the operators in a separate `parse_rules!` invocation to section them from the rest of the rules.

For ternary and associativity you can check out https://github.com/d3lio/lexpar/blob/067ed17a968c4bc03872af45f911437056384def/examples/ml_family/parser/mod.rs#L123

If you're trying to do a Rust-like or C-like `if` then you can do something like `[If, LParen, ex: expr, RParen]`

Here's the DSL I've implemented with the library: https://github.com/d3lio/degu-lang
On the README.md you can see the use of the ifs.
To understand how the parser works - it takes a token from the iterator and tries to match it to the arms in the rules from top to bottom. If the token matches to an arm it goes in it, skipping the rest of the branches. If a non-terminal is called the parses goes into recursion wich progresses the iterator. Something like `if expr1 then expr2` where `if` and `then` are tokens and `expr*` is nonterm, the `expr` will be parsed before trying to parse `then` so `if a then if b then c` will parse the first inner expression then the `then` then the second inner expression as if it was `if (a) then (if (b) then (c))` considering the if-then-else as an expression. With the same effect you can replace the keywords `then` with `?` and `else` with `:`
If you want you can play around with the nonterms and tokens and the order of branches to achieve different precidence/associativity.

I haven't had much time to add more examples and to support the library but I think the docs have most cases covered. If you can't do something you can always use https://docs.rs/lexpar/0.1.0/lexpar/parser/index.html#custom-handlers to do arbitraty parsing.


Hopefully I was able to give you the info you need and explain why and how it works.

**Comment by d3lio** [comment]
I just realized that the ternary would be a bit more special since you don't have a begining keyword and you straight out start with an expression so here's another thing you can try:

```rust
expr: Expr => {
    [ex: inner_expr, tern: ternary] => {
        // ...
    }
}

// inner_expr: ... (other exprs)

ternary: Option<(Expr, Expr)> => {
    ["?", then: expr, ":", el: expr] => {
        Some((then, el))
    },
    [@] => None
}
```

I haven't tested it, it might need some tweaks, let me know if you get it to work.
